[package]
name = "async-osc"
version = "1.0.0"
description = "Heavy Modded Async "
readme = "README.md"
edition = "2018"
keywords = ["osc", "vrchat", "async-std"]
authors = ["Giggle Tech <hello@giggletech.io>"
]

[features]

[dependencies]
rosc = "0.4.2"
async-std = { version = "1.8.0", features = ["attributes", "unstable"] }
#async-std =  "1.12.0"
log = "0.4.14"
futures-lite = "1.11.3"
thiserror = "1.0.24"
configparser = "3.0.2"
lazy_static = "1.4.0"
tokio = { version = "1.13", features = ["full"] }
futures = "0.3"
#ini = "1.3.0"
anyhow = "1.0.44"
once_cell = "1.8.0"
yaml-rust = "0.4.5"
reqwest = { version = "0.11", features = ["json", "blocking"] } # HTTP client library, with support for JSON and blocking requests
execute = "0.2.13"                        # Library for easily executing system commands
dirs = "4.0"                              # Library to retrieve platform-specific directories (like AppData)
serde = { version = "1.0", features = ["derive"] }  # Serialization/deserialization framework, with support for `derive`
serde_yaml = "0.9"                        # YAML support for `serde`
rocket = "0.5.0-rc.1"
hyper = { version = "0.14", features = ["full"] }
async-h1 = "2.3.4"
tide = "0.16"






[dev-dependencies]
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
